import { StressScenario } from './types';

export const PREDEFINED_SCENARIOS: StressScenario[] = [
  {
    id: '2008-financial-crisis',
    name: '2008 Financial Crisis',
    description: 'Lehman Brothers collapse triggers global credit freeze. All asset prices plunge, correlations spike to 1, and liquidity evaporates.',
    category: 'historical',
    version: '1.0.0',
    created: '2024-01-01T00:00:00Z',
    priceChanges: [
      { asset: 'XLM', changePercent: -50 },
      { asset: 'BTC', changePercent: -45 },
      { asset: 'ETH', changePercent: -50 },
      { asset: 'USDC', changePercent: -5 },
    ],
    correlationShifts: [
      { asset1: 'XLM', asset2: 'BTC', newCorrelation: 0.95 },
      { asset1: 'XLM', asset2: 'ETH', newCorrelation: 0.95 },
      { asset1: 'BTC', asset2: 'ETH', newCorrelation: 0.95 },
    ],
    volatilityMultipliers: [
      { asset: 'XLM', multiplier: 4.0 },
      { asset: 'BTC', multiplier: 3.5 },
      { asset: 'ETH', multiplier: 3.5 },
    ],
    tags: ['systemic', 'credit-crunch', 'contagion'],
  },
  {
    id: '2020-covid-crash',
    name: '2020 COVID-19 Market Crash',
    description: 'Global pandemic triggers circuit breakers across all markets. Sharp 35-40% drawdown in days, followed by aggressive monetary response.',
    category: 'historical',
    version: '1.0.0',
    created: '2024-01-01T00:00:00Z',
    priceChanges: [
      { asset: 'XLM', changePercent: -40 },
      { asset: 'BTC', changePercent: -50 },
      { asset: 'ETH', changePercent: -55 },
      { asset: 'USDC', changePercent: -8 },
    ],
    correlationShifts: [
      { asset1: 'XLM', asset2: 'BTC', newCorrelation: 0.85 },
    ],
    volatilityMultipliers: [
      { asset: 'XLM', multiplier: 3.5 },
      { asset: 'BTC', multiplier: 4.0 },
      { asset: 'ETH', multiplier: 4.5 },
    ],
    cascadingLiquidation: true,
    tags: ['black-swan', 'pandemic', 'liquidity-crisis'],
  },
  {
    id: 'luna-ust-collapse',
    name: 'Luna/UST Collapse',
    description: 'Algorithmic stablecoin death spiral wipes out $40B. Collateral value collapses to near-zero, triggering massive lending protocol liquidations.',
    category: 'historical',
    version: '1.0.0',
    created: '2024-01-01T00:00:00Z',
    priceChanges: [
      { asset: 'XLM', changePercent: -60 },
      { asset: 'BTC', changePercent: -35 },
      { asset: 'ETH', changePercent: -40 },
      { asset: 'USDC', changePercent: -15 },
    ],
    correlationShifts: [
      { asset1: 'XLM', asset2: 'BTC', newCorrelation: 0.9 },
      { asset1: 'XLM', asset2: 'ETH', newCorrelation: 0.9 },
    ],
    volatilityMultipliers: [
      { asset: 'XLM', multiplier: 6.0 },
      { asset: 'BTC', multiplier: 3.0 },
      { asset: 'ETH', multiplier: 3.5 },
    ],
    cascadingLiquidation: true,
    tags: ['stablecoin', 'death-spiral', 'contagion'],
  },
  {
    id: '3ac-ftx-contagion',
    name: '3AC/FTX Contagion Event',
    description: 'Major crypto hedge fund and exchange insolvencies trigger cascading liquidations across DeFi lending protocols.',
    category: 'historical',
    version: '1.0.0',
    created: '2024-01-01T00:00:00Z',
    priceChanges: [
      { asset: 'XLM', changePercent: -30 },
      { asset: 'BTC', changePercent: -25 },
      { asset: 'ETH', changePercent: -30 },
      { asset: 'USDC', changePercent: -3 },
    ],
    correlationShifts: [
      { asset1: 'XLM', asset2: 'BTC', newCorrelation: 0.8 },
      { asset1: 'XLM', asset2: 'ETH', newCorrelation: 0.85 },
      { asset1: 'BTC', asset2: 'ETH', newCorrelation: 0.85 },
    ],
    volatilityMultipliers: [
      { asset: 'XLM', multiplier: 4.5 },
      { asset: 'BTC', multiplier: 3.5 },
      { asset: 'ETH', multiplier: 4.0 },
    ],
    cascadingLiquidation: true,
    tags: ['contagion', 'counterparty-risk', 'exchange-risk'],
  },
  {
    id: 'rate-hike-shock',
    name: 'Aggressive Rate Hike Cycle',
    description: 'Central banks raise rates by 300-400bps. Risk assets reprice, stablecoin yields surge, and leveraged positions unwind.',
    category: 'hypothetical',
    version: '1.0.0',
    created: '2024-01-01T00:00:00Z',
    priceChanges: [
      { asset: 'XLM', changePercent: -25 },
      { asset: 'BTC', changePercent: -20 },
      { asset: 'ETH', changePercent: -25 },
      { asset: 'USDC', changePercent: 0 },
    ],
    correlationShifts: [],
    volatilityMultipliers: [
      { asset: 'XLM', multiplier: 2.5 },
      { asset: 'BTC', multiplier: 2.0 },
      { asset: 'ETH', multiplier: 2.5 },
    ],
    tags: ['macro', 'interest-rate', 'risk-off'],
  },
  {
    id: 'stablecoin-depeg',
    name: 'Stablecoin Depegging Event',
    description: 'Major stablecoin loses its peg. Collateral denominated in stablecoin loses value, triggering margin calls and liquidations.',
    category: 'hypothetical',
    version: '1.0.0',
    created: '2024-01-01T00:00:00Z',
    priceChanges: [
      { asset: 'USDC', changePercent: -20 },
      { asset: 'XLM', changePercent: -15 },
      { asset: 'BTC', changePercent: -10 },
    ],
    correlationShifts: [
      { asset1: 'USDC', asset2: 'XLM', newCorrelation: 0.6 },
    ],
    volatilityMultipliers: [
      { asset: 'USDC', multiplier: 10.0 },
      { asset: 'XLM', multiplier: 3.0 },
    ],
    cascadingLiquidation: true,
    tags: ['stablecoin', 'depeg', 'margin-call'],
  },
  {
    id: 'flash-crash',
    name: 'Multi-Asset Flash Crash',
    description: 'Sudden 30% drop across all major assets within minutes. Circuit breakers fail, DEX liquidity dries up.',
    category: 'hypothetical',
    version: '1.0.0',
    created: '2024-01-01T00:00:00Z',
    priceChanges: [
      { asset: 'XLM', changePercent: -30 },
      { asset: 'BTC', changePercent: -30 },
      { asset: 'ETH', changePercent: -30 },
      { asset: 'USDC', changePercent: -5 },
    ],
    correlationShifts: [
      { asset1: 'XLM', asset2: 'BTC', newCorrelation: 0.95 },
      { asset1: 'XLM', asset2: 'ETH', newCorrelation: 0.95 },
      { asset1: 'BTC', asset2: 'ETH', newCorrelation: 0.95 },
    ],
    volatilityMultipliers: [
      { asset: 'XLM', multiplier: 5.0 },
      { asset: 'BTC', multiplier: 4.5 },
      { asset: 'ETH', multiplier: 5.0 },
    ],
    cascadingLiquidation: true,
    durationSteps: 5,
    tags: ['flash-crash', 'liquidity-crisis', 'fast-recovery'],
  },
  {
    id: 'oracle-manipulation',
    name: 'Oracle Manipulation Attack',
    description: 'Coordinated attack manipulates oracle prices by 30% on one major asset. Protocol must detect and reject manipulated prices.',
    category: 'hypothetical',
    version: '1.0.0',
    created: '2024-01-01T00:00:00Z',
    priceChanges: [
      { asset: 'XLM', changePercent: 30 },
      { asset: 'BTC', changePercent: 0 },
      { asset: 'ETH', changePercent: 0 },
      { asset: 'USDC', changePercent: 0 },
    ],
    correlationShifts: [
      { asset1: 'XLM', asset2: 'BTC', newCorrelation: 0.3 },
    ],
    volatilityMultipliers: [
      { asset: 'XLM', multiplier: 8.0 },
    ],
    tags: ['oracle', 'manipulation', 'exploit'],
  },
];

export const CUSTOM_SCENARIO_TEMPLATE: StressScenario = {
  id: 'custom',
  name: 'Custom Scenario',
  description: 'User-defined stress scenario',
  category: 'custom',
  version: '1.0.0',
  created: new Date().toISOString(),
  priceChanges: [],
  correlationShifts: [],
  volatilityMultipliers: [],
  tags: ['custom'],
};
