[package]
name = "hello-world"
version = "0.0.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib", "lib"]
doctest = false

[dependencies]
shared-events = { path = "../shared-events" }
stellarlend-flash-loan = { package = "flash-loan", path = "../flash-loan" }
soroban-sdk = { workspace = true }
soroban-token-sdk = { workspace = true }
stellarlend-amm = { path = "../amm" }
stellarlend-oracle-client = { path = "../../packages/oracle-client" }
stellarlend-shared-deadline = { path = "../shared-deadline" }
stellar-contract-utils = { version = "0.7.2" }
stellar-macros = { version = "0.6.0" }

[dev-dependencies]
soroban-sdk = { workspace = true, features = ["testutils"] }
stellarlend-lending = { path = "../lending" }
