[package]
name = "batch-operations"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
soroban-sdk = { version = "20.5.0", features = ["contracttype"] }
soroban-token-sdk = "20.5.0"
calldata-encoding = { path = "../lib/calldata-encoding" }

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
